# As there are no releases in GN, we build the latest tag from time to time.
# The version is the time of the latest master commit in YYYYMMDDHHMMSS
# notation.

{% set name = "gn" %}
{% set version = "0.0.20200320191924" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # We have to use git as the source as the provided tarballs are not stable.
  git_url: https://gn.googlesource.com/gn
  git_rev: 5ed3c9cc67b090d5e311e4bd2aba072173e82db9
  patches:
    - add-lrt.patch  # [linux]

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - ninja
  host:
  run:

test:
  commands:
    - test -f $PREFIX/bin/gn

about:
  home: https://gn.googlesource.com/gn/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'GN is a meta-build system that generates build files for Ninja.'

extra:
  recipe-maintainers:
    - xhochy
