# As there are no releases in GN, we build the latest tag from time to time.
# The version is the time of the latest master commit in YYYYMMDDHHMMSS
# notation.

{% set name = "gn" %}
{% set version = "0.0.20260526193358" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # We have to use git as the source as the provided tarballs are not stable.
  git_url: https://gn.googlesource.com/gn
  git_rev: 3357c4f51b1a9e676378c695dd9c7e9911c35ee6  # 2026-05-26; matches pdfium chromium/7891 DEPS

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - ninja
    - git
  run:

test:
  commands:
    - test -f $PREFIX/bin/gn

about:
  home: https://gn.googlesource.com/gn/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'GN is a meta-build system that generates build files for Ninja.'

extra:
  recipe-maintainers:
    - xhochy
