travis:
  secure:
    BINSTAR_TOKEN: A6v3I8uHTONq/GPizc/V5AvV7jY2lmHluKVmVIPs9V8kO+9STWU2priurAqb6gDKH2+TEtHmxgeGas0lXuWaBJ0PZoEBNRgN629WKlzfdlVM4L03seLd/0b626F29xdBxtGnEcJQjgtCr4bh0BCVzf6jC8cKNPTlZ2Q5vIF/qWmXQF1rMthVoXMvg0HliQ8QKJiNd+n9tFmYFH9CEus9JZ9j+jSn/UcMXqce3L60vGoy56T8L+chOEH1/TApQzlyyTBpI07zcsXNUdoPvbbGRTQVCqB3yw2ScEpLfVwyhAHt3biZ1+5ZXpXJx2dmzIWecEG6VE0pgrSrPBf83EnEBXTQJD1OkreJPZcyIiDtu1v9uvfIr6+Xy2P/Z2+BCfQz0o989rWyV80cGNfjVcSL0Y4Gofirj2u66ZW+39W8uVQ7aldp9dsZ16WAUQ21/07qd9RGUbvxjRzxMaymeiw/6ttz3IGPuW7vKbbYkz6rUXqUxl8k8FQRI86lNdUnWu5AF5LCkM84HV9CwQMT7gMXzF61XSUIGdUxOCgkOQ95rnXrW4qqY0ex/Wx1LofVzJf3fEYlHT+nNUtOGikaCobVM9U2Me+p1VpdwvR5PM7zzbBpHC0SCm/8t+R/8h1IM2HBO9CJcHCJJuwi84W7WMNdh/Im9eIpMIx9rwRgIu86C2o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
